sudo: false
language: scala
scala: 2.11.7
jdk:
- oraclejdk8
notifications:
  slack:
    secure: UmQFzNGthz7nbCiC31+oXItsDxYRgEl0Gmbm8jKeU89kHGmAO8cAIcAX7J8GNj2vfryYCglg3/xU19Nv31cCfaNQOmr2oT6QFiOfrRurmvICQH4pwbQSg2J9X3q2HChVTwDqUWEjWQq5P6mzTI3QxMf5UxIATjiDZOWd7jFEAw8+6xuFlOR8KOxS6l5v+J9lTfEd/O3cJ77oWkz9Aw6B0VIsksTJu7X2y7E5AGOUybSdrYbEo2Wi/Jq+/AqoyBN+wD+5h6mK0bx3a3K8x0EJHqOtgg4FB/090PhvBApo58dI7ep1b5QLZ+gATQi/DKvRSU7NxuUcIwQjsKy78ile8Q2XmMFs+HXYNNALKSzJNijuufifbI6KyQWlysVX6MQd6VFweZAgu6ihaGFsy0Aqw4ESUIyK7atSmGvW64wFZwqemULBGUzE9o1BMUthdmHWU6HGyyqxOEI8kI/oMVgpledL+f9kZzpm5pku7CTY8e6VPex+VlIkJ7c/eksdTdLPROhLuThIZXtWfm0vWpoqexxYczFjsoKm6od3Wi/fvlD/g3C4oqDff3wQ5iEDaW4rQVVEkchUuDFqaYtgYh8zWqweWZNQJwgTElfX5zDk3rwV1dkq6wbWlOdtfn9SI5Jlqtfa1/kGN3ZxqX4EvO1GJJfhvOuT9a5acbgrXL9eFaU=
